[project]
name = "proxy-be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "samypr100", email = "3933065+samypr100@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
proxy-be = "proxy_be:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
